### PR TITLE
Add `formFactor` property to `UADataValues`

### PR DESCRIPTION
**Pull request by faisalman**
Hi, thanks for the types! I'm using it and just made a small update to also include the recently added `formFactor` data: https://wicg.github.io/ua-client-hints/#sec-ch-ua-form-factor

### CODE REVIEW

**Comment by lukewarlow** [comment]
Thanks for this!

**Comment by lukewarlow** [comment]
This is released in 0.4.1. The type as per https://wicg.github.io/ua-client-hints/#dom-uadatavalues-formfactor is actually just a string not a string[] just in case you notice that difference when you upgrade.

Thanks for pointing out I was missing this property!

**Comment by faisalman** [comment]
I was referring to it at first, but judging by this commit (that's just pushed yesterday): https://github.com/WICG/ua-client-hints/commit/65215d82e19ac43599c8fead9f3f94eafdad2bfd I just thought it might eventually get changed into a `string[]` later.

**Comment by lukewarlow** [comment]
Ah thanks for pointing me to that. I'll keep an eye out for any changes and am happy to update the types once the Ua Data Spec / Chrome implementation changes :)

**Comment by lukewarlow** [comment]
I've left a comment https://github.com/WICG/ua-client-hints/pull/343#issuecomment-1710252943 trying to get clarification on this

**Comment by lukewarlow** [comment]
@faisalman as an update the spec has been corrected so I've changed it back to an array and released 0.4.2. Apologies for that back and forth. Thanks once again!

**Comment by faisalman** [comment]
Thanks to you! Happy to help :+1:

**Pull request merged**
